services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      N8N_SECURE_COOKIE: false
      WEBHOOK_URL: __N8N_HOST__

volumes:
  n8n_data:
