services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    network_mode: host
    volumes:
      - /opt/n8n-data:/home/node/.n8n
    restart: unless-stopped
    environment:
      N8N_SECURE_COOKIE: false
      WEBHOOK_URL: __N8N_WEBHOOK_URL__
      PORT: __N8N_PORT__
